// <auto-generated />
namespace PUCEntityFrameworkMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class version2Removedfromdisplayname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version2Removedfromdisplayname));
        
        string IMigrationMetadata.Id
        {
            get { return "201703120957405_version2-Removed-from-display-name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
