// <auto-generated />
namespace PUCEntityFrameworkMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class version3updatesemestertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version3updatesemestertable));
        
        string IMigrationMetadata.Id
        {
            get { return "201703121043172_version3-update-semester-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
